"""
Model B: Transaction Fraud Detection using XGBoost (primary) and Random
Forest (comparison), matching your tech stack doc.

Data expected -- one of:
    1. data/synthetic_transactions.csv
       -> Generated by generate_synthetic_transactions.py (works out of the box)
    2. A real Kaggle dataset, reshaped to the same columns:
       amount, is_new_recipient, country, device_type, device_trust_score,
       transaction_hour, prior_transaction_count, is_fraud
       -> IEEE-CIS: https://www.kaggle.com/c/ieee-fraud-detection
       -> Credit Card Fraud (ULB): https://www.kaggle.com/mlg-ulb/creditcardfraud
       Both need feature remapping since they use card-not-present features,
       not bank-transfer features -- see the README for notes on this gap.

Run:
    python train_fraud_model.py --data data/synthetic_transactions.csv

Output:
    saved_models/fraud_xgboost_model.joblib
    saved_models/fraud_random_forest_model.joblib
    saved_models/fraud_feature_encoder.joblib
"""
import argparse
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, classification_report, confusion_matrix,
)
from xgboost import XGBClassifier
import joblib

CATEGORICAL_COLS = ["country", "device_type"]
NUMERIC_COLS = ["amount", "is_new_recipient", "device_trust_score",
                "transaction_hour", "prior_transaction_count"]
TARGET_COL = "is_fraud"
MODEL_DIR = "saved_models"


def build_features(df: pd.DataFrame, encoder: OneHotEncoder = None, fit: bool = False):
    if fit:
        encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
        cat_encoded = encoder.fit_transform(df[CATEGORICAL_COLS])
    else:
        cat_encoded = encoder.transform(df[CATEGORICAL_COLS])

    cat_df = pd.DataFrame(
        cat_encoded, columns=encoder.get_feature_names_out(CATEGORICAL_COLS), index=df.index
    )
    X = pd.concat([df[NUMERIC_COLS].reset_index(drop=True), cat_df.reset_index(drop=True)], axis=1)
    return X, encoder


def evaluate(name: str, model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    print(f"\n=== {name} evaluation ===")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision: {precision_score(y_test, y_pred):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
    print(f"F1 Score:  {f1_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC:   {roc_auc_score(y_test, y_proba):.4f}")
    print(f"PR-AUC:    {average_precision_score(y_test, y_proba):.4f}  "
          f"(more informative than ROC-AUC given class imbalance)")
    print("\nClassification report:")
    print(classification_report(y_test, y_pred, target_names=["legitimate", "fraud"]))
    print("Confusion matrix (rows=true, cols=pred) [legitimate, fraud]:")
    print(confusion_matrix(y_test, y_pred))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="data/synthetic_transactions.csv")
    args = parser.parse_args()

    os.makedirs(MODEL_DIR, exist_ok=True)

    if not os.path.exists(args.data):
        raise FileNotFoundError(
            f"{args.data} not found. Run generate_synthetic_transactions.py first, "
            f"or point --data at a real dataset reshaped to the expected columns."
        )

    df = pd.read_csv(args.data)
    print(f"Loaded {len(df)} transactions. Fraud rate: {df[TARGET_COL].mean():.2%}")

    X, encoder = build_features(df, fit=True)
    y = df[TARGET_COL]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Handle class imbalance via scale_pos_weight (ratio of negative to positive).
    scale_pos_weight = (y_train == 0).sum() / max((y_train == 1).sum(), 1)

    xgb_model = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.08,
        subsample=0.8,
        colsample_bytree=0.8,
        scale_pos_weight=scale_pos_weight,
        eval_metric="aucpr",
        random_state=42,
    )
    xgb_model.fit(X_train, y_train)
    evaluate("XGBoost", xgb_model, X_test, y_test)

    rf_model = RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    rf_model.fit(X_train, y_train)
    evaluate("Random Forest", rf_model, X_test, y_test)

    # Feature importance from XGBoost -- useful for your AI Explanation Engine.
    importances = pd.Series(xgb_model.feature_importances_, index=X.columns).sort_values(ascending=False)
    print("\n=== Top feature importances (XGBoost) ===")
    print(importances.head(10))

    joblib.dump(xgb_model, os.path.join(MODEL_DIR, "fraud_xgboost_model.joblib"))
    joblib.dump(rf_model, os.path.join(MODEL_DIR, "fraud_random_forest_model.joblib"))
    joblib.dump(encoder, os.path.join(MODEL_DIR, "fraud_feature_encoder.joblib"))
    print(f"\nSaved models + encoder to {MODEL_DIR}/")


if __name__ == "__main__":
    main()
