"""
Model A (MVP baseline): SMS Phishing Classifier using TF-IDF + Logistic
Regression -- this is the "Alternative (Hackathon)" option from your own
tech stack doc, and is realistic to train and demo within hackathon time
(seconds, CPU-only), unlike full BERT fine-tuning.

For the full BERT/AraBERT version, see train_bert_finetune.py.

Data expected:
    1. data/sms_spam_collection.csv
       -> Download from https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset
          Columns after rename: message, label ("ham"/"spam")
       -> This is ENGLISH ONLY.
    2. data/arabic_english_sms_samples.csv
       -> Generated by generate_arabic_sms_samples.py (label: "safe"/"phishing")

The script merges both, maps labels to a common {safe, phishing} scheme,
and trains/evaluates a classifier.

Run:
    python train_tfidf_baseline.py

Output:
    saved_models/sms_tfidf_vectorizer.joblib
    saved_models/sms_logreg_model.joblib
"""
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, classification_report, confusion_matrix,
)
import joblib

# Pluggable dataset registry -- to add a new dataset, edit sms_datasets.py,
# NOT this file. This script never needs to know which datasets exist.
from sms_datasets import load_all_sms_data

MODEL_DIR = "saved_models"


def load_data():
    return load_all_sms_data()


def clean_text(text: str) -> str:
    # Light cleaning only -- aggressive stemming/stopword removal tends to
    # hurt TF-IDF less than you'd think, but keep it minimal and transparent.
    return text.lower().strip()


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    df = load_data()
    print(f"\nTotal training rows: {len(df)}")
    print(df["label"].value_counts())

    df["message_clean"] = df["message"].apply(clean_text)
    y = (df["label"] == "phishing").astype(int)  # 1 = phishing, 0 = safe

    X_train, X_test, y_train, y_test = train_test_split(
        df["message_clean"], y, test_size=0.2, random_state=42, stratify=y
    )

    vectorizer = TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        sublinear_tf=True,
    )
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    model = LogisticRegression(max_iter=1000, class_weight="balanced")
    model.fit(X_train_vec, y_train)

    y_pred = model.predict(X_test_vec)
    y_proba = model.predict_proba(X_test_vec)[:, 1]

    print("\n=== Evaluation ===")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision: {precision_score(y_test, y_pred):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
    print(f"F1 Score:  {f1_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC:   {roc_auc_score(y_test, y_proba):.4f}")
    print("\nClassification report:")
    print(classification_report(y_test, y_pred, target_names=["safe", "phishing"]))
    print("Confusion matrix (rows=true, cols=pred) [safe, phishing]:")
    print(confusion_matrix(y_test, y_pred))

    joblib.dump(vectorizer, os.path.join(MODEL_DIR, "sms_tfidf_vectorizer.joblib"))
    joblib.dump(model, os.path.join(MODEL_DIR, "sms_logreg_model.joblib"))
    print(f"\nSaved model + vectorizer to {MODEL_DIR}/")

    # Quick sanity check with example messages.
    examples = [
        "Dear Alinma customer, your account will be blocked. Click here immediately: http://alinma-verify.xyz",
        "عزيزي عميل بنك الإنماء، حسابك سيتم إيقافه اليوم. تحقق فورًا عبر الرابط",
        "Your OTP is 483921",
        "رمز التحقق الخاص بك هو 4821",
    ]
    examples_vec = vectorizer.transform([clean_text(e) for e in examples])
    preds = model.predict(examples_vec)
    probs = model.predict_proba(examples_vec)[:, 1]
    print("\n=== Sanity check ===")
    for msg, pred, prob in zip(examples, preds, probs):
        label = "phishing" if pred == 1 else "safe"
        print(f"[{label} ({prob:.2%})] {msg}")


if __name__ == "__main__":
    main()
