"""
Model B: Transaction Fraud / Risk Engine.

ARCHITECTURE (mirrors sms_classifier.py)
----------------------------------------
  1. SCORE  -- trained XGBoost model (ml-training/fraud_model/train_fraud_model.py)
  2. REASON -- transparent rule engine below, for the human explanation (FR7)

The model decides; the rules explain. "0.87 fraud probability" is useless to
a customer -- "the recipient is new and the amount is 6x your normal spending"
is actionable.

*** IMPORTANT HONESTY NOTE -- READ BEFORE QUOTING ANY METRIC ***
The XGBoost model currently shipped was trained on SYNTHETIC transactions
generated by ml-training/data/generate_synthetic_transactions.py. That
generator creates fraud rows using explicit rules (fraudulent rows get
larger amounts, riskier countries, lower device trust). XGBoost therefore
learned those same rules back -- which is why it scores ~100% on that data.

That number measures "can XGBoost re-learn the rules we used to fabricate
the data", NOT "can it detect real bank fraud". It is circular. Do not
present it as fraud-detection accuracy.

What IS legitimately true and worth saying:
  - The full pipeline (features -> model -> score -> explanation -> alert)
    is built, integrated, and running.
  - Swapping in real Alinma transaction data requires only retraining;
    no code changes here.
  - The feature set (amount, new beneficiary, destination, device trust,
    hour, history depth) is the same set real fraud systems use.

MODEL BACKEND (env var TXN_MODEL_BACKEND):
    auto   (default) -- use XGBoost if it loads, else rules
    model            -- require XGBoost; raise if unavailable
    rules            -- force the rule engine

Model files expected in backend/saved_models/:
    fraud_xgboost_model.joblib
    fraud_feature_encoder.joblib
Copy them there with scripts/copy_model.ps1 after training.
"""
import logging
import os
import threading
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODEL_DIR = os.getenv("TXN_MODEL_DIR", os.path.join(_BACKEND_DIR, "saved_models"))
MODEL_FILE = os.path.join(MODEL_DIR, "fraud_xgboost_model.joblib")
ENCODER_FILE = os.path.join(MODEL_DIR, "fraud_feature_encoder.joblib")
TXN_MODEL_BACKEND = os.getenv("TXN_MODEL_BACKEND", "auto").lower()

# Feature order MUST match training (train_fraud_model.py).
NUMERIC_COLS = ["amount", "is_new_recipient", "device_trust_score",
                "transaction_hour", "prior_transaction_count"]
CATEGORICAL_COLS = ["country", "device_type"]

DEFAULT_TYPICAL_AMOUNT = 3000.0
HIGH_RISK_COUNTRIES = {"PK", "NG", "RU", "UA"}  # illustrative placeholder


@dataclass
class TransactionRiskResult:
    risk_score: float          # 0-1 fraud probability
    risk_level: str            # "low" | "medium" | "high"
    recommended_action: str    # "approve" | "verify" | "reject"
    explanation: str
    reasons: list = field(default_factory=list)


# ---------------------------------------------------------------------------
# Rule engine -- explanations, and the fallback score
# ---------------------------------------------------------------------------
def _rule_reasons_and_score(amount, is_new_recipient, country,
                            device_trust_score, user_typical_amount):
    reasons, score = [], 0.0

    if user_typical_amount > 0 and amount > user_typical_amount * 3:
        score += 0.35
        reasons.append("the amount significantly exceeds this customer's typical spending")
    elif user_typical_amount > 0 and amount > user_typical_amount * 1.5:
        score += 0.15
        reasons.append("the amount is higher than usual for this customer")

    if is_new_recipient:
        score += 0.25
        reasons.append("the recipient has never been used before")

    country_code = (country or "SA").upper()
    if country_code != "SA":
        score += 0.15
        reasons.append(f"the transfer is going to a foreign destination ({country_code})")
    if country_code in HIGH_RISK_COUNTRIES:
        score += 0.15
        reasons.append("the destination country has an elevated fraud rate")

    if device_trust_score < 50:
        score += 0.20
        reasons.append("it was initiated from an unrecognized or low-trust device")
    elif device_trust_score < 80:
        score += 0.08
        reasons.append("the device trust score is below normal")

    return reasons, min(score, 1.0)


# ---------------------------------------------------------------------------
# XGBoost backend (lazy singleton)
# ---------------------------------------------------------------------------
class _FraudModel:
    _instance: Optional["_FraudModel"] = None
    _lock = threading.Lock()
    _load_failed = False

    def __init__(self):
        import joblib
        import pandas as pd
        self._pd = pd
        self.model = joblib.load(MODEL_FILE)
        self.encoder = joblib.load(ENCODER_FILE)
        logger.info("Transaction risk: loaded XGBoost from %s", MODEL_FILE)

    @classmethod
    def get(cls) -> Optional["_FraudModel"]:
        if cls._load_failed:
            return None
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None and not cls._load_failed:
                    try:
                        cls._instance = cls()
                    except Exception as e:
                        cls._load_failed = True
                        logger.warning(
                            "Transaction risk: XGBoost unavailable (%s). Using the "
                            "rule engine. Expected model at %s", e, MODEL_FILE)
                        return None
        return cls._instance

    def predict_proba(self, amount, is_new_recipient, country, device_type,
                      device_trust_score, transaction_hour,
                      prior_transaction_count) -> float:
        pd = self._pd
        row = pd.DataFrame([{
            "amount": float(amount),
            "is_new_recipient": int(bool(is_new_recipient)),
            "device_trust_score": float(device_trust_score),
            "transaction_hour": int(transaction_hour),
            "prior_transaction_count": int(prior_transaction_count),
            "country": (country or "SA").upper(),
            "device_type": device_type or "mobile",
        }])
        # Two training pipelines exist for this model:
        #   * backend/train_models.py            -> OrdinalEncoder (in-place)
        #   * ml-training/fraud_model/train_fraud_model.py -> OneHotEncoder
        # Auto-detect the encoder type so artifacts from either pipeline load.
        from sklearn.preprocessing import OrdinalEncoder
        if isinstance(self.encoder, OrdinalEncoder):
            # OrdinalEncoder replaces categoricals in-place (same column count).
            # Feature order must match training: NUMERIC_COLS then CATEGORICAL_COLS.
            row[CATEGORICAL_COLS] = self.encoder.transform(row[CATEGORICAL_COLS])
            X = row[NUMERIC_COLS + CATEGORICAL_COLS]
        else:
            cat = self.encoder.transform(row[CATEGORICAL_COLS])
            cat_df = pd.DataFrame(cat, columns=self.encoder.get_feature_names_out(CATEGORICAL_COLS))
            X = pd.concat([row[NUMERIC_COLS].reset_index(drop=True),
                           cat_df.reset_index(drop=True)], axis=1)
        return float(self.model.predict_proba(X)[0, 1])


def txn_model_status() -> dict:
    """Which backend is serving transaction risk? Log at startup."""
    if TXN_MODEL_BACKEND == "rules":
        return {"backend": "rules", "reason": "forced by TXN_MODEL_BACKEND=rules"}
    m = _FraudModel.get()
    if m is not None:
        return {"backend": "xgboost", "model_file": MODEL_FILE,
                "trained_on": "synthetic data -- see module docstring before "
                              "quoting accuracy"}
    if TXN_MODEL_BACKEND == "model":
        raise RuntimeError(f"TXN_MODEL_BACKEND=model but {MODEL_FILE} could not load.")
    return {"backend": "rules", "reason": f"XGBoost unavailable at {MODEL_FILE}"}


# ---------------------------------------------------------------------------
# Public API -- old signature preserved; new params are optional, so
# routers/transactions.py keeps working unchanged.
# ---------------------------------------------------------------------------
def score_transaction(
    amount: float,
    is_new_recipient: bool,
    country: Optional[str],
    device_trust_score: float = 100.0,
    user_typical_amount: float = DEFAULT_TYPICAL_AMOUNT,
    device_type: str = "mobile",
    transaction_hour: Optional[int] = None,
    prior_transaction_count: int = 20,
) -> TransactionRiskResult:
    # Rules always run: they produce the explanation regardless of scorer.
    reasons, rule_score = _rule_reasons_and_score(
        amount, is_new_recipient, country, device_trust_score, user_typical_amount)

    if transaction_hour is None:
        transaction_hour = datetime.now().hour

    score, model_used = None, False
    if TXN_MODEL_BACKEND != "rules":
        model = _FraudModel.get()
        if model is not None:
            try:
                score = model.predict_proba(
                    amount, is_new_recipient, country, device_type,
                    device_trust_score, transaction_hour, prior_transaction_count)
                model_used = True
            except Exception as e:
                logger.error("Transaction risk: inference failed (%s); using rules", e)

    if score is None:
        if TXN_MODEL_BACKEND == "model":
            raise RuntimeError(f"XGBoost required but unavailable ({MODEL_FILE})")
        score = rule_score

    if score >= 0.7:
        risk_level = "high"
        action = "reject" if score >= 0.9 else "verify"
    elif score >= 0.35:
        risk_level = "medium"
        action = "verify"
    else:
        risk_level = "low"
        action = "approve"

    # Only present rule reasons as *flags* when the verdict is actually
    # elevated. Otherwise you get "Flagged because the amount exceeds normal"
    # attached to a LOW/approve verdict, which contradicts itself.
    if risk_level == "low":
        if reasons and model_used:
            explanation = ("This transaction is within normal risk. Minor factors noted: "
                           + "; ".join(reasons) + ".")
        else:
            explanation = "This transaction matches the customer's normal behavior pattern."
    elif reasons:
        prefix = (f"The AI model rates this {score * 100:.0f}/100 for fraud risk. "
                  f"Flagged because " if model_used else "This transfer is unusual because ")
        explanation = prefix + "; ".join(reasons) + "."
    else:
        explanation = (f"The AI model rates this {score * 100:.0f}/100 for fraud risk "
                       f"based on the overall pattern, though no individual factor "
                       f"stands out. Additional verification is recommended.")

    return TransactionRiskResult(
        risk_score=round(score, 3),
        risk_level=risk_level,
        recommended_action=action,
        explanation=explanation,
        reasons=reasons,
    )
